### ISSUE TITLE
Loot dont claim all loot... bugging

### ISSUE THREAD

**Issue by Xpatro** [Xarano-GIT/Faster-Loot#1]
im having a problem that the addon is "looting to fast" so that it dont grab all the loot but i need to click sometimes 2+ times extra to get ALL loot.

- dont know why this happens

**Comment by Xarano-GIT** [comment]
Unfortunately, this is a game bug, not caused by loot addons.

https://us.forums.blizzard.com/en/wow/t/bug-auto-loot-is-not-working-100-of-the-time/1899515
